### ISSUE TITLE
why many repos under rockchip-linux are gone

### ISSUE THREAD

**Issue by amazingfate** [JeffyCN/mirrors#1]
I want to download some files in repo https://github.com/rockchip-linux/rk-rootfs-build/, but I can't find the repo. I also find that other many repos are gone. Why did this happen? Can I find the missing repos somewhere else?

**Comment by JeffyCN** [comment]
those are temporary shutdown for some unspeakable reasons :(

for the rootfs-build, you can checkout the debian branch here

**Comment by JeffyCN** [comment]
There's another mirror at:
https://github.com/Caesar-github/rk-rootfs-build
