### ISSUE TITLE
HDMI output issue on RK3568 - kernel 4.19.193 - linux

### ISSUE THREAD

**Issue by avafinger** [JeffyCN/mirrors#1]
Hi @JeffyCN  / @HermanChen 
I have a black screen for HDMI output on RK3568. HDMI output works fine on RK3399.
How can I troubleshoot HDMI?
Radxa kernel 4.19.193 works fine for HDMI but it is somewhat outdated.

No kernel message error for HDMI

```
[    0.451780] rockchip-drm display-subsystem: Linked as a consumer to fe0a0000.hdmi
[    0.455410] dwhdmi-rockchip fe0a0000.hdmi: Detected HDMI TX controller v2.11a with HDCP (DWC HDMI 2.0 TX PHY)
[    0.456262] dwhdmi-rockchip fe0a0000.hdmi: registered DesignWare HDMI I2C bus driver
[    0.457217] rockchip-drm display-subsystem: bound fe0a0000.hdmi (ops 0xffffff8008fa66a8)
[    1.195352] asoc-simple-card hdmi-sound: i2s-hifi <-> fe400000.i2s mapping ok
[    1.866690]   #0: rockchip,hdmi

```

**Comment by JeffyCN** [comment]
sorry, i don't know much about HDMI.

356x is using the new VOP2 HW module, which brings lots of issues. so maybe try the newest kernel:
https://github.com/JeffyCN/mirrors/tree/kernel-4.19

if still has issues, i'd prefer:
1/ connect your business window to create an issue in rockchip's redmine issue system.
or
2/ find the recent committer of the related codes, and mail them.
for example HDMI should be:
kernel-4.19/drivers/gpu/drm/rockchip# git log -10 *hdmi*|grep Author|sort|uniq
Author: Algea Cao <algea.cao@rock-chips.com>
Author: Andy Yan <andy.yan@rock-chips.com>
Author: Sandy Huang <hjc@rock-chips.com>
Author: Zheng Yang <zhengyang@rock-chips.com>
