### ISSUE TITLE
rk3562 support

### ISSUE THREAD

**Issue by axililsz** [JeffyCN/mirrors#13]
```shell
*** No rule to make target 'arch/arm64/boot/dts/rockchip/rk3562-evb1-lp4x-v10-linux.dtb'.  Stop.
```
when use yocto build for rk3562

**Comment by JeffyCN** [comment]
sorry, i've been warned not to provide newer 5.10 kernel.. so the mirror kernel 5.10 here is too old for that chip.

maybe you can try to use some other rockchip 5.10 kernel source in github, for example radxa.
