### ISSUE TITLE
Request to sync the librga mirror to version 1.10.0

### ISSUE THREAD

**Issue by nyanmisaka** [JeffyCN/mirrors#15]
Could you please synchronize the librga source code to version [1.10.0](https://github.com/airockchip/librga/commit/46b58ca032a59568c9241e2791aa5c24459d7127)?

[airockchip/librga](https://github.com/airockchip/librga) only provides pre-built libs, some of my use cases require modifying the code in librga. Thanks in advance!

能否麻烦你将 librga 源代码同步到 [1.10.0](https://github.com/airockchip/librga/commit/46b58ca032a59568c9241e2791aa5c24459d7127) 版本？

[Airockchip/librga](https://github.com/airockchip/librga) 仅提供预构建的库，我的一些用例需要修改 librga 中的代码。非常感谢。@JeffyCN

**Comment by JeffyCN** [comment]
done
