### ISSUE TITLE
5.10 kernel on rk3568 HDMI driver assumes vo1_gpu exists. 

### ISSUE THREAD

**Issue by shawn-pfister** [JeffyCN/mirrors#2]
dw_hdmi-rochchip.c 1293

`hdmi->vo1_regmap = syscon_regmap_lookup_by_phandle(np, "rockchip,vo1_grf");`

Maybe check if `ddc_en_reg == RK3568_GRF_VO_CON1` before trying to parse it. I commented it out and everything seemed to work.

**Comment by JeffyCN** [comment]
this repo is just a mirror, for kernel related issues, please report to rockchip's redmine issue system, or mail the related commiters :)

**Comment by JeffyCN** [comment]
and for what i know, 3568 is using 4.19 bsp kernel, 5.10 kernel is 3588 only for now.
