### ISSUE TITLE
[rkwifibt] rename AP6275P NVRAM config file

### ISSUE THREAD

**Issue by dylad** [JeffyCN/mirrors#28]
Rockchip Linux kernel didn't find by default the file nvram_AP6275P.txt file when using  an image generated by Yocto. In fact, Linux kernel expects this filename to be all lowercase.
nvram_AP6275P.txt -> nvram_ap6275p.txt

An update on meta-rockchip will be needed after that (I can provide one if needed).
I do not know if this issue also affects Buildroot.

**Comment by CmST0us** [comment]
I meet this problem too!, 
Hope the upstream will fix this

**Comment by JeffyCN** [comment]
i've updated a patch for this, should be ok now

**Comment by dylad** [comment]
Thanks @JeffyCN
