### ISSUE TITLE
Android Termux mali g52 default kernel supports?

### ISSUE THREAD

**Issue by Mateus2022** [JeffyCN/mirrors#29]
I am using proot with ubuntu 23 I am using mali g52 phone I got bad performance llvm how to install libmali firmware for g52/panfork mesa?

**Comment by Mateus2022** [comment]
I using llvm I not installed panfork/firmware my gpu not support libmali

**Comment by JeffyCN** [comment]
sorry, don't know anything about android or llvm, maybe you can ask it in the related mail list

**Comment by JeffyCN** [comment]
panfork has a maillist i think

**Comment by Mateus2022** [comment]
Pls add 0x7212
