### ISSUE TITLE
Request to sync the librga mirror to version 1.10.1_[0]

### ISSUE THREAD

**Issue by nyanmisaka** [JeffyCN/mirrors#31]
Could you please sync the librga sources to version [1.10.1_[0]](https://github.com/airockchip/librga/commit/75af4ddd89893311779ddbd3d4c0b9a7ef5d0cfc)?

It's the first version to support RK3576.

Thanks in advance! @JeffyCN

**Comment by JeffyCN** [comment]
done :)

**Comment by nyanmisaka** [comment]
Thx again for your instant response :p
