### ISSUE TITLE
linux 6.1 rkr4.1 

### ISSUE THREAD

**Issue by hbiyik** [JeffyCN/mirrors#33]
is it possible for you to update rkr4.1 bsp? I couldnt find any clean version nowhere..

**Comment by JeffyCN** [comment]
sorry, i'm not allowed to upgrade kernel sources.

maybe you can check armbian github

**Comment by hbiyik** [comment]
Found them

https://github.com/radxa/kernel/commits/linux-6.1-stan-rkr4.1-buildroot/

https://github.com/armbian/linux-rockchip/tree/linux-6.1-stan-rkr4.1
