### ISSUE TITLE
BGR to NV12 Color Conversion Is Greener Than Expected

### ISSUE THREAD

**Issue by jesusvigil** [JeffyCN/mirrors#35]
I am trying to convert a BGR video to the NV12 format but the resulting colors in the NV12 video appear greener than expected. As an example, with the below GStreamer pipleine, I used videotestsrc to generate smpte75 pattern. The Magenta value should be RGB (191,0,191) but when using RGA to convert, you get the an RGB value for magenta (204,29,194) which indicates there's more green in that color range than expected.
<img width="674" alt="with-rga-magenta-rgb-value" src="https://github.com/user-attachments/assets/8078fa72-69da-4fdc-a551-9f56acf6f817">

Additionally, I tested without using RGA and found that it accurately converted colors to an RGB value of (191,1,190)
<img width="670" alt="no-rga-magenta-rgb-value" src="https://github.com/user-attachments/assets/473248ad-2840-44a4-aca6-b719c5d57700">

The below is the pipeline I used to generate test videos. I use `GST_VIDEO_CONVERT_USE_RGA=1` to use RGA and in another test it's not in my env so I can use native videoconvert.

I have tested using rga_api `1.10.1_[3]` and `MPP 1.0.7`
```
gst-launch-1.0 -e -v \
	videotestsrc pattern=smpte75 ! video/x-raw,format=BGR,width=1920,height=1080 \
	! queue ! videoconvert ! video/x-raw,format=NV12,colorimetry=bt709 \
	! queue ! videorate ! video/x-raw,framerate=60/1 \
	! queue ! mpph264enc ! h264parse \
	! queue ! mux. isofmp4mux name=mux fragment-duration=3200000000 latency=1000000000 ! filesink location=/home/user/Documents/out.mp4 sync=true
```

Is there an issue with my pipeline or perhaps the RGA library? An advise is greatly appreciated!

**Comment by JeffyCN** [comment]
sorry, i don't know rga, please report to rga maintainer(committor)

might be something wrong with color range
