### ISSUE TITLE
Gstreamer mppvideodec crop-rectangle function is not working

### ISSUE THREAD

**Issue by BlueBrightWind** [JeffyCN/mirrors#36]
I used the command: gst-launch-1.0 filesrc location=/path/to/the/video.mp4 ! qtdemux ! h264parse ! mppvideodec format="BGR" crop-rectangle="<50,50,50,50>" ! appsink to create a GStreamer pipeline, but the decoded image is not cropped as expected. It is same as the image without using the crop-rectangle.

I also used the command: gst-launch-1.0 filesrc location=/path/to/the/video.mp4 ! qtdemux ! h264parse ! mppvideodec crop-rectangle="<50, 50, 50, 50>" ! fakesink, and the load of the RGA is 0%, indicating that rga has not done the crop function.

I have tested the following command: gst-launch-1.0 filesrc location=/path/to/the/video.mp4 ! qtdemux ! h264parse ! mppvideodec format="BGR" width=1920 height=1080 ! appsink, and observed the load of RGA by checking the /sys/kernel/debug/rkrga/load file, indicating that RGA is working. In this command, the image can be scaled to the specified size correctly. 

Is the reason why it is not working properly due to my incorrect command or some other issue? How can I make the crop-rectangle function work correctly? Thank you very much

**Comment by JeffyCN** [comment]
it's passing a crop meta to the downstream plugin(kmssink/waylandsink).

for your appsink, you might need to do the cropping in it, using rga maybe

**Comment by BlueBrightWind** [comment]
So the mppvideodec plugin will process the resize operation through rga, and for the crop-rectangle operation, it will only pass the metadata to downstream plugins without performing the cropping process on the image, is that correct?

**Comment by JeffyCN** [comment]
right, the downstream plugins might be able to do it faster(for example waylandsink's opengles)

**Comment by BlueBrightWind** [comment]
Ok I know，thank you very much
