### ISSUE TITLE
libmali g24 with RK3588 (non -S) Wayland not found

### ISSUE THREAD

**Issue by HeyMeco** [JeffyCN/mirrors#38]
With libmali-valhall-g610-g24p0-wayland-gbm on ubuntu noble wayland is broken and doesn’t initialize on RK3588 without S:

g13 "worked" in wayland on RK3588

Error on RK3588 is:
```
connect(6, {sa_family=AF_UNIX, sun_path="/run/user/1000/wayland-0"}, 27) = -1 ENOENT (No such file or directory)
```
Working example on RK3588S:
```
connect(6, {sa_family=AF_UNIX, sun_path="/run/user/1000/wayland-0"}, 27) = 0
```

**Comment by SergeyKharenko** [comment]
@HeyMeco Could you please tell me how you ultimately resolved this issue? I'm encountering a similar problem on Armbian (kernel 6.1.99) with GNOME as the desktop environment and Wayland as the display server. After installing the `g24p0`, it fails to render properly. However, the `g13p0` works.
