### ISSUE TITLE
Add kernel-5.10 branch?

### ISSUE THREAD

**Issue by tmm1** [JeffyCN/mirrors#6]
Can we have `kernel-5.10` mirror like `kernel-4.4` and `kernel-4.19` mirror?

Currently there is a `kernel-5.10-2022_01_10` tag used by `linux-rockchip_5.10.bb`, but no branch.

**Comment by JeffyCN** [comment]
i've been warned not to provide 5.10 kernel, due to company policy :(

**Comment by tmm1** [comment]
Understood, thanks. Maybe you can push a new tag which matches 5.10.110 from `develop-5.10` branch on https://github.com/rockchip-linux/kernel/tree/develop-5.10
