### ISSUE TITLE
linux-rga-im2d分支平台重复写的代码有点冗余

### ISSUE THREAD

**Issue by jiale-gdyd** [JeffyCN/mirrors#7]
很多这样的代码:
#if defined(__arm64__) || defined(__aarch64__)
xxxxxxx
#else
yyyyyyy
#endif

这其实就是几个参数的类型不一致而已，而重复写了多次这样的接口，不如改成这样:
#if defined(__arm64__) || defined(__aarch64__)
typedef unsigned long arch_type_t;
#else
typedef unsigned int arch_type_t;
#endif

然后利用arch_type_t去合并那几个变量的类型

**Comment by JeffyCN** [comment]
sorry, i don't maintain librga, please contact the author or committers.
